data <- read.csv('balanced panel for 160 countries (2007-2014).csv')
str(data)

# plot
plot(~DEMO+LAW+CORRUPT+LNINCOMEPC+INEQUALITY+URBAN+EDU_IDX+LNK+LNL2,data=data)
plot(~CORRUPT+LNINCOMEPC+INEQUALITY+LAW+URBAN,data=data)
plot(~EDU_IDX+LNINCOMEPC+LAW+INEQUALITY,data=data)
plot(~LNY+INEQUALITY+LAW+LNK+LNL2+URBAN,data=data)

# OLS
mod_EDU_OLS <- lm(EDU_IDX~LNINCOMEPC+LAW+INEQUALITY+dCIVILWARS+dFRENCH+
                dBRITISH+dLANDLOCKED+dLATINAME+dMIDEAST+dOIL+dPOSTSOVIET+dWENA , data = data)
summary(mod_EDU_OLS)

# Panel data, random-effect
mod_EDU_RE <- plm(EDU_IDX~LNINCOMEPC+LAW+INEQUALITY+dCIVILWARS+dFRENCH+
                    dBRITISH+dLANDLOCKED+dLATINAME+dMIDEAST+dOIL+dPOSTSOVIET+dWENA , data = data,
                  index=c("Country","year"), model="random")
summary(mod_EDU_RE)

# system of equations
library(systemfit)

r1<-DEMO~LNINCOMEPC+LAW+dCIVILWARS+dFRENCH+dBRITISH+dLANDLOCKED+
  dLATINAME+dMIDEAST+dOIL+dPOSTSOVIET+dWENA
r2<-CORRUPT~LNINCOMEPC+INEQUALITY+LAW+URBAN+dCIVILWARS+dFRENCH+
  dBRITISH+dLANDLOCKED+dLATINAME+dMIDEAST+dOIL+dPOSTSOVIET+dWENA
r3<-EDU_IDX~LNINCOMEPC+LAW+INEQUALITY+dCIVILWARS+dFRENCH+
  dBRITISH+dLANDLOCKED+dLATINAME+dMIDEAST+dOIL+dPOSTSOVIET+dWENA
r4<-LNY~INEQUALITY+LAW+LNK+LNL2+URBAN+dCIVILWARS+dFRENCH+
  dBRITISH+dLANDLOCKED+dLATINAME+dMIDEAST+dOIL+dPOSTSOVIET+dWENA  

eqSystem_SUR <- list(modDEMO = r1, modCORRUPT = r2, modEDU = r3, modLNY = r4)
fitsur <- systemfit(eqSystem_SUR, data=data, method="SUR")
summary(fitsur)

